### ISSUE TITLE
Support Java 7 please

### ISSUE THREAD

**Issue by abdelrahman-sinno** [mikolajmitura/java-properties-to-json#17]
I am really in need to make use of this library in my JDK 7 project; I have searched and no other libraries are available.

Could you please advise on code changes to be done so this compiles on JDK 7 ?

If I try to update the project myself, is there any difficulty I should be aware of before starting ?

Much thanks.

**Comment by mikolajmitura** [comment]
Hello, 
I will make change for JDK 7, after that I will share you jar, because deploy to maven repo will take some time.

**Comment by mikolajmitura** [comment]
for now you can download jar from https://drive.google.com/file/d/0B13-N6gR1O-DeWNJdG8tOWpzOG8/view?usp=sharing
In few hours jar will available from maven repo.

**Comment by mikolajmitura** [comment]
Please try with 1.2, it was compiled with java 7. 

<dependency>
          <groupId>pl.jalokim.propertiestojson</groupId>
          <artifactId>java-properties-to-json</artifactId>
          <version>1.2</version>
 </dependency>
