### ISSUE TITLE
incorrect handling for integer and boolean

### ISSUE THREAD

**Issue by alexyezhigang** [mikolajmitura/java-properties-to-json#20]
currenttly, integer will parse to double which had change the actual value, for example 123 to 123.00 and boolen will parse to "true", "false" which was expected as true and false

**Comment by mikolajmitura** [comment]
Thanks for issue. I will add feature which parse simple numbers as integer, and boolean as true or false value.

**Comment by mikolajmitura** [comment]
The version 1.3 should be available from maven central repository in few hours. 

<dependency>
    <groupId>pl.jalokim.propertiestojson</groupId>
    <artifactId>java-properties-to-json</artifactId>
    <version>1.3</version>
</dependency>

**Comment by mikolajmitura** [comment]
Now the version 1.3 is available from maven central repo.
