### ISSUE TITLE
Boolean values don't always serialize

### ISSUE THREAD

**Issue by thejeff77** [mikolajmitura/java-properties-to-json#28]
Boolean variables are not in the output - at least if they are false.

ex: 

env.something = false
env.somethingelse = false

Results in:

{}

**Comment by mikolajmitura** [comment]
Hm, 
String s = PropertiesToJsonParser.parsePropertiesFromFileToJson("src/main/resources/prop.properties");
System.out.println(s);
for me it return: 
{"env":{"somethingelse":false,"something":false}}

/prop.properties
env.something = false
env.somethingelse = false

Can you give me which method you used? And how?

**Comment by mikolajmitura** [comment]
String s = PropertiesToJsonParser.parsePropertiesFromFileToJson("src/main/resources/prop.properties","test");
then it will return empty json:
{}

but for PropertiesToJsonParser.parsePropertiesFromFileToJson("src/main/resources/prop.properties","env");
it should return: 
{"env":{"somethingelse":false,"something":false}}

but for 
PropertiesToJsonParser.parsePropertiesFromFileToJson("src/main/resources/prop.properties","env.somethingelse");
{"env":{"somethingelse":false}}

**Comment by thejeff77** [comment]
Sorry for not being very specific! Its the method that takes in Java.util.Properties as a memory object. Its not the one that reads the file itself. I'm parsing from a yaml file, so this is the only method I can use - passing it in after its parsed and read into memory.

I'll provide a code example after I get to work.

**Comment by thejeff77** [comment]
```
System.out.println("Before json: " + props.toString());
String publicJson = PropertiesToJsonParser.parseToJson(props);
System.out.println(publicJson);
```
Outputs:
`Before json: {env.hasLandingPage=false, env.metricsEnabled=false}
{}
`

**Comment by mikolajmitura** [comment]
Version 2.2 was deployed addressed this issue.
