### ISSUE TITLE
Switch off arrayWithDelimeter

### ISSUE THREAD

**Issue by bond-it** [mikolajmitura/java-properties-to-json#31]
Can I switch off interpretation of property content as array?

This is my example:
`validations.address=Address can contain digits, letters`
I have json as:
`"validations":{
      "address":[
         "Address can contain digits",
         "letters"
      ]
   }`

I want to have:
`"validations":{
      "address": "Address can contain digits, letters"
   }`

Is it possible with your library?

**Comment by bond-it** [comment]
> Or I can add feature which will let users of library to provide type resolvers.
Maybe it's better resolve. In my case I need only StringJsonTypeResolver.

**Comment by mikolajmitura** [comment]
You can use the 3.0 version of tool.
