### ISSUE TITLE
Properties key access from a custom PrimitiveJsonTypeResolver

### ISSUE THREAD

**Issue by niark567** [mikolajmitura/java-properties-to-json#34]
Hi,

I have a use case where I need a PrimitiveJsonTypeResolver to know/use the propertiesKey known by the PrimitiveJsonTypesResolver (inherited from JsonTypeResolver).
The idea is so just to let the custom PrimitiveJsonTypeResolver have access to this protected field by providing a simple getter.

Sincerely,
Julian.

**Comment by niark567** [comment]
I made a PR for this #35

**Comment by mikolajmitura** [comment]
Thank you for your comment na PR :-) it will be helpful for others :-)

**Comment by niark567** [comment]
Tanks for merging and for this projet ;)
