### ISSUE TITLE
Empty value issue

### ISSUE THREAD

**Issue by ghassen1433** [mikolajmitura/java-properties-to-json#37]
I have a problem when I need to convert a file that contained a null value.

**Comment by mikolajmitura** [comment]
Hi, 
Thank you for your issue. 

What do you expect when properties has empty? 
json with below? 
```json 
{
"new"=""
}
```
or 
```json 
{
"new"=null
}
```

In my opinion when will be empty 
props:
"new=" then 

json should be 
{
"new"=""
}

and when 
new=null

result json:
{
"new"=null
}

Do you like this? Can you confirm this?

**Comment by ghassen1433** [comment]
Hello thank you for the response,
i went to convert a .properties file to a json file using PropertiesToJsonConverter().parsePropertiesFromFileToJson() method

I have this file "config.properties"
   qsqsqs=qsqsqs
   auditLogging.fileName=${LOG_LOCATION}/jc_audit
   new=
   azazaz=false

when your code try to convert the "new" propertie, it will crash.

**Comment by mikolajmitura** [comment]
please check local build of below branch:
https://github.com/mikolajmitura/java-properties-to-json/tree/bugfix/37_empty_property

to build project you can only type:
``` console
mvn clean install 
```

**Comment by ghassen1433** [comment]
Great,
i confirm that the bug was fixed
Thank you.
