### ISSUE TITLE
Preserving order of properties [question]

### ISSUE THREAD

**Issue by hicnar** [mikolajmitura/java-properties-to-json#64]
Does this library have an option to preserve order when creating json? 
By this I mean with the properties looking as follows:

object.property1=Prop1
object.property2-Prop2
object.nested.property3=Nested

the resulting json would be

```
"object": {
 "property1: "Prop1".
"property2": "Prop2",
"nested": {
 "property3": "Nested"
}
}

```
in this exact order?

And if this is not supported, do you reckon it would take lots of effort to add such feature?

Pozdrawiam! :)

**Comment by mikolajmitura** [comment]
Hi, 
Sorry for late reply. Githug doesn't notifying me via email...
Thanks for your question :-)

For read properties from file or by inputStrem order should be kept. 
So read by methods:
```java
String jsonFromProperties = new PropertiesToJsonConverter().convertPropertiesFromFileToJson("/home/user/file.properties");

String jsonFromProperties2 = new PropertiesToJsonConverter().convertPropertiesFromFileToJson(new File("/home/user/file.properties"));
```

But if doesn't work let me know.
Which methods you are using? 
Which version of lib you are using?

From version 5.1.3 keeping order should work.

Pozdrawiam! :-)
